INDEX_TEMPLATE = 'index.html'
AUTHED_INDEX_TEMPLATE = 'index-authorized.html'
OAUTH_TEMPLATE = 'oauth.html'
GENERATE_DONE_TEMPLATE = 'generate.html'
NOTHING_TO_POST_TEMPLATE = 'post-nothing.html'
POST_TEMPLATE = 'post.html'
COOKIE_USERNAME = 'markov_twitter_username'
