
response = {u'contributors': None,
 u'coordinates': None,
 u'created_at': u'Tue Aug 24 05:50:57 +0000 2010',
 u'favorited': False,
 u'geo': None,
 u'id': 21977739295L,
 u'in_reply_to_screen_name': None,
 u'in_reply_to_status_id': None,
 u'in_reply_to_user_id': None,
 u'place': None,
 u'retweet_count': None,
 u'retweeted': False,
 u'source': u'MarkovTweet',
 u'text': u'None',
 u'truncated': False,
 u'user': {u'contributors_enabled': False,
           u'created_at': u'Wed Nov 05 06:17:54 +0000 2008',
           u'description': u'professional software engineer // gadget geek // dog lover // father',
           u'favourites_count': 2,
           u'follow_request_sent': False,
           u'followers_count': 252,
           u'following': False,
           u'friends_count': 345,
           u'geo_enabled': True,
           u'id': 17183483,
           u'lang': u'en',
           u'listed_count': 21,
           u'location': u'Albuquerque, NM, USA',
           u'name': u'Jason Mobarak',
           u'notifications': False,
           u'profile_background_color': u'1A1B1F',
           u'profile_background_image_url': u'http://a3.twimg.com/profile_background_images/26079111/3524309323_58cb018a96.jpg',
           u'profile_background_tile': True,
           u'profile_image_url': u'http://a3.twimg.com/profile_images/449024663/twitterProfilePhoto_normal.jpg',
           u'profile_link_color': u'2FC2EF',
           u'profile_sidebar_border_color': u'181A1E',
           u'profile_sidebar_fill_color': u'252429',
           u'profile_text_color': u'666666',
           u'profile_use_background_image': True,
           u'protected': False,
           u'screen_name': u'silverjam',
           u'show_all_inline_media': False,
           u'statuses_count': 2133,
           u'time_zone': u'Mountain Time (US & Canada)',
           u'url': u'http://csjam.blogspot.com',
           u'utc_offset': -25200,
           u'verified': False}}


